[phase.setup]
nixpkgsArchive = 'd0a406bf79d281e5bfbede3a7721b4d6115bcb2c'

[build]
dependsOn = ["node"]

[build.commands]
install = "npm ci"
build = "npm run build"

[start]
cmd = "nginx -g 'daemon off;'"
