name: CI

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

jobs:
    # Linting on pull_request only
    lint:
        runs-on: ubuntu-latest
        if: ${{ github.event.pull_request }}

        strategy:
            matrix:
                node-version: [20.x]

        steps:
            - uses: actions/checkout@v3

            - name: Linting check
              uses: actions/setup-node@v3
              with:
                  node-version: ${{matrix.node-version}}
                  cache: npm

            - name: Install packages
              run: npm ci

            - name: Run linter
              run: npm run lint

    # Build task
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [20.x]

        steps:
            - uses: actions/checkout@v3

            - name: Setup Node.js environment ${{matrix.node-version}}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{matrix.node-version}}
                  cache: npm

            - name: Install packages
              run: npm ci

            - name: Run tests
              run: npm run test:ci

            - name: Build
              run: npm run build
            # Use this action to publish to server
            # https://github.com/marketplace/actions/scp-files
